#include <et/core/et.h>
#include "material.cpp"
#include "rendering.cpp"
#include "vertexbufferfactory.cpp"
#include "base\helpers.cpp"
#include "base\indexarray.cpp"
#include "base\primitives.cpp"
#include "base\renderbatch.cpp"
#include "base\vertexarray.cpp"
#include "base\vertexdatachunk.cpp"
#include "base\vertexdeclaration.cpp"
#include "base\vertexstorage.cpp"

#if (ET_PLATFORM_WIN)
#	include "dx12\dx12_indexbuffer.cpp"
#	include "dx12\dx12_pipelinestate.cpp"
#	include "dx12\dx12_program.cpp"
#	include "dx12\dx12_renderer.cpp"
#	include "dx12\dx12_renderpass.cpp"
#	include "dx12\dx12_texture.cpp"
#	include "dx12\dx12_vertexbuffer.cpp"
#	include "vulkan\vulkan.cpp"
#	include "vulkan\vulkan_indexbuffer.cpp"
#	include "vulkan\vulkan_pipelinestate.cpp"
#	include "vulkan\vulkan_program.cpp"
#	include "vulkan\vulkan_renderer.cpp"
#	include "vulkan\vulkan_renderpass.cpp"
#	include "vulkan\vulkan_texture.cpp"
#	include "vulkan\vulkan_vertexbuffer.cpp"
#endif

#if (ET_PLATFORM_MAC)
#	include "metal\metal.mm"
#	include "metal\metal_indexbuffer.mm"
#	include "metal\metal_pipelinestate.mm"
#	include "metal\metal_program.mm"
#	include "metal\metal_renderer.mm"
#	include "metal\metal_renderpass.mm"
#	include "metal\metal_texture.mm"
#	include "metal\metal_vertexbuffer.mm"
#endif

#include "opengl\opengl.cpp"
#include "opengl\opengl_caps.cpp"
#include "opengl\opengl_framebuffer.cpp"
#include "opengl\opengl_indexbuffer.cpp"
#include "opengl\opengl_materialfactory.cpp"
#include "opengl\opengl_pipelinestate.cpp"
#include "opengl\opengl_program.cpp"
#include "opengl\opengl_renderer.cpp"
#include "opengl\opengl_renderpass.cpp"
#include "opengl\opengl_texture.cpp"
#include "opengl\opengl_vertexarrayobject.cpp"
#include "opengl\opengl_vertexbuffer.cpp"
